name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20.15.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          path: .output
