name: deploy-to-production-env

on:
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:20.15.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Check code with ESLint and Prettier
        run: npm run check
      - name: Build
        run: npm run build
      - name: copy output files via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: ".output/"
          target: "~/"
